@echo off
echo Killing process on port 8081...
npx kill-port 8081
echo Already in project directory...
echo Clearing npm cache...
npm cache clean --force
echo Removing old dependencies...
if exist node_modules ( rd /s /q node_modules )
if exist package-lock.json ( del package-lock.json )
echo Installing dependencies...
npm install
echo Creating .env file if it does not exist...
if not exist .env ( copy .env.example .env )
echo Clearing expo cache...
npx expo start --clear
echo Starting dev server...
start "Expo Dev Server" npx expo start --web --port 8081 --host localhost
